kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: ghost
  namespace: argo
spec:
  project: deploy
  source:
    repoURL: https://github.com/AmielDylan/sre-project.git
    targetRevision: main
    path: ghost
    helm:
      valueFiles: 
        - values.yaml
      values: |
        # Réduis Ghost
        resourcesPreset: "nano"
        
        # MySQL avec image OFFICIELLE
        mysql:
          image:
            registry: docker.io
            repository: mysql
            tag: "8.0"
            pullPolicy: IfNotPresent
          
          # Réduis les ressources
          primary:
            resourcesPreset: "nano"
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
  destination:
      namespace: app
      server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
